[package]
name = "rustique-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "rustique_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
audio-engine = { path = "../../../crates/audio-engine" }
exporter = { path = "../../../crates/exporter" }
pollster = "0.4"
project-format = { path = "../../../crates/project-format" }
raw-window-handle = "0.6"
render-core = { path = "../../../crates/render-core" }
serde = { version = "1", features = ["derive"] }
simulation = { path = "../../../crates/simulation" }
tauri = { version = "2", features = [] }
tokio = { version = "1", features = ["rt-multi-thread"] }
wgpu = "24"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
