import { create } from "zustand";
export type ModulationSource = "sub" | "bass" | "low_mids" | "mids" | "high_mids" | "highs" | "rms" | "transient" | "spectral_centroid" | "spectral_flux";
export type ModulationTarget = "gravity_strength" | "particle_size" | "brightness" | "hue_shift" | "burst_emission" | "camera_fov" | "camera_shake" | "material_roughness" | "reflection_intensity" | "surface_scale" | "volume_density" | "volume_motion" | "droplet_density" | "droplet_size" | "droplet_refraction" | "droplet_gravity" | "flocking_separation" | "flocking_cohesion" | "flocking_turbulence" | "flocking_speed" | "flocking_randomness" | "flocking_impulse";
export interface ModulationMapping { enabled: boolean; source: ModulationSource; target: ModulationTarget; amount: number; offset: number; minimum: number; maximum: number; polarity: "normal" | "inverted"; curve: "linear" | "exponential"; attack_seconds: number; release_seconds: number; }
export interface ProfileSelection { source: string; overrides: Record<string, unknown>; }
export interface ProjectData { project_version: number; engine_version: string; seed: number; fps: number; duration_seconds: number; particle_system: { count: number; substeps: number; emitter: unknown }; forces: unknown[]; camera: Record<string, unknown> & { mode: "static" | "orbit"; vertical_fov_degrees: number; orbit_degrees_per_second: number; shake_amplitude: number }; render_defaults: { width: number; height: number; particle_size_pixels: number; background: number[] }; modulation_mappings: ModulationMapping[]; automation_tracks: AutomationTrack[]; scene_markers: SceneMarker[]; visual_preset: unknown | null; analysis_profile: ProfileSelection | null; reaction_profile: ProfileSelection | null; }
export interface AutomationKeyframe { time_seconds: number; value: number; }
export interface AutomationTrack { target: ModulationTarget; enabled: boolean; keyframes: AutomationKeyframe[]; }
export interface SceneMarker { time_seconds: number; label: string; }
export interface ParameterSchema { path: string; label: string; kind: "number" | "toggle" | "color"; minimum: number | null; maximum: number | null; step: number | null; modulationTarget: ModulationTarget | null; }
export interface MacroSchema { id: string; label: string; target: string; minimum: number; maximum: number; default: number; }
export interface EditorProject { path: string; project: ProjectData; parameters: ParameterSchema[]; macros: MacroSchema[]; }
interface EditorState { document: EditorProject | null; dirty: boolean; setDocument: (document: EditorProject) => void; replaceProject: (project: ProjectData, dirty?: boolean) => void; }
export const useEditorStore = create<EditorState>((set) => ({ document: null, dirty: false, setDocument: (document) => set({ document, dirty: false }), replaceProject: (project, dirty = true) => set((state) => ({ document: state.document ? { ...state.document, project } : null, dirty })) }));
