import { useEffect, useRef, useState, type PointerEvent } from "react";
import type { TimelineAudio } from "./native";
import type { ModulationTarget, ProjectData } from "./store";

const targets: ModulationTarget[] = ["gravity_strength", "particle_size", "brightness", "burst_emission", "camera_fov", "camera_shake"];
const pretty = (value: string) => value.replaceAll("_", " ");
interface Props { project: ProjectData | null; audio: TimelineAudio | null; cursorSeconds: number; slice: [number, number]; onSeek: (seconds: number) => void; onProjectChange: (project: ProjectData) => void; onSliceChange: (range: [number, number]) => void; }

export function Timeline({ project, audio, cursorSeconds, slice, onSeek, onProjectChange, onSliceChange }: Props) {
  const canvas = useRef<HTMLCanvasElement>(null); const [zoom, setZoom] = useState(1); const [viewStart, setViewStart] = useState(0); const [selection, setSelection] = useState<[number, number]>(slice); const dragStart = useRef<number | null>(null);
  const duration = project?.duration_seconds ?? audio?.durationSeconds ?? 1; const visibleDuration = duration / zoom; const maxStart = Math.max(0, duration - visibleDuration); const start = Math.min(viewStart, maxStart); const end = start + visibleDuration;
  useEffect(() => {
    const clampedRange: [number, number] = [Math.min(slice[0], duration), Math.min(slice[1], duration)];
    setSelection(clampedRange);
    if (clampedRange[0] !== slice[0] || clampedRange[1] !== slice[1]) onSliceChange(clampedRange);
  }, [duration, onSliceChange]);
  useEffect(() => { const element = canvas.current; if (!element) return; const context = element.getContext("2d"); if (!context) return; const scale = window.devicePixelRatio; const width = element.clientWidth; const height = element.clientHeight; element.width = Math.round(width * scale); element.height = Math.round(height * scale); context.scale(scale, scale); context.fillStyle = "#0b0d12"; context.fillRect(0, 0, width, height); const xAt = (time: number) => (time - start) / visibleDuration * width;
    if (audio?.waveform.length) { context.strokeStyle = "#7f8b9d"; context.beginPath(); const bucketDuration = audio.durationSeconds / audio.waveform.length; audio.waveform.forEach(([minimum, maximum], index) => { const time = (index + 0.5) * bucketDuration; if (time < start || time > end) return; const x = xAt(time); context.moveTo(x, height * (0.5 - maximum * 0.42)); context.lineTo(x, height * (0.5 - minimum * 0.42)); }); context.stroke(); }
    context.fillStyle = "rgba(216,255,98,.12)"; context.fillRect(xAt(selection[0]), 0, xAt(selection[1]) - xAt(selection[0]), height); context.strokeStyle = "#ff9862"; for (const time of audio?.transientTimes ?? []) { if (time >= start && time <= end) { const x = xAt(time); context.beginPath(); context.moveTo(x, 0); context.lineTo(x, 12); context.stroke(); } } context.strokeStyle = "#67b7ff"; for (const time of audio?.beatTimes ?? []) { if (time >= start && time <= end) { const x = xAt(time); context.beginPath(); context.moveTo(x, 0); context.lineTo(x, height); context.stroke(); } } context.strokeStyle = "#d8ff62"; context.lineWidth = 2; const cursorX = xAt(cursorSeconds); context.beginPath(); context.moveTo(cursorX, 0); context.lineTo(cursorX, height); context.stroke();
    for (const marker of project?.scene_markers ?? []) { if (marker.time_seconds >= start && marker.time_seconds <= end) { const x = xAt(marker.time_seconds); context.fillStyle = "#eebcff"; context.fillRect(x - 2, height - 13, 4, 13); } }
  }, [audio, cursorSeconds, duration, end, project?.scene_markers, selection, start, visibleDuration]);
  function eventTime(event: PointerEvent<HTMLCanvasElement>) { const bounds = event.currentTarget.getBoundingClientRect(); return Math.max(0, Math.min(duration, start + (event.clientX - bounds.left) / bounds.width * visibleDuration)); }
  function pointerDown(event: PointerEvent<HTMLCanvasElement>) { const time = eventTime(event); dragStart.current = time; setSelection([time, time]); event.currentTarget.setPointerCapture(event.pointerId); }
  function pointerMove(event: PointerEvent<HTMLCanvasElement>) { if (dragStart.current === null) return; const time = eventTime(event); setSelection([Math.min(dragStart.current, time), Math.max(dragStart.current, time)]); }
  function pointerUp(event: PointerEvent<HTMLCanvasElement>) { const time = eventTime(event); if (dragStart.current !== null && Math.abs(time - dragStart.current) < 0.02) onSeek(time); dragStart.current = null; }
  function addTrack() { if (!project) return; onProjectChange({ ...project, automation_tracks: [...project.automation_tracks, { target: "brightness", enabled: true, keyframes: [] }] }); }
  function addKeyframe(trackIndex: number) { if (!project) return; const tracks = structuredClone(project.automation_tracks); const track = tracks[trackIndex]; const existing = track.keyframes.find((key) => Math.abs(key.time_seconds - cursorSeconds) < 0.001); if (existing) existing.value = 1; else track.keyframes.push({ time_seconds: cursorSeconds, value: 1 }); track.keyframes.sort((a, b) => a.time_seconds - b.time_seconds); onProjectChange({ ...project, automation_tracks: tracks }); }
  return <div className="timeline-editor"><div className="timeline-toolbar"><label>Zoom <input type="range" min="1" max="20" step="1" value={zoom} onChange={(e) => setZoom(Number(e.target.value))} /></label><label>Scroll <input type="range" min="0" max={maxStart} step="0.01" value={start} disabled={maxStart === 0} onChange={(e) => setViewStart(Number(e.target.value))} /></label></div>
    <canvas ref={canvas} className="waveform-canvas" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} />
    <div className="range-grid"><label>Selection start<input type="number" min="0" max={duration} step="0.1" value={selection[0].toFixed(2)} onChange={(e) => setSelection([Number(e.target.value), selection[1]])}/></label><label>Selection end<input type="number" min="0" max={duration} step="0.1" value={selection[1].toFixed(2)} onChange={(e) => setSelection([selection[0], Number(e.target.value)])}/></label><button onClick={() => onSliceChange(selection)}>Use as preview slice</button><span>Slice {slice[0].toFixed(2)}–{slice[1].toFixed(2)}s</span></div>
    <div className="timeline-tracks"><div className="section-title"><h3>Automation</h3><button onClick={addTrack} disabled={!project}>+ Track</button></div>{project?.automation_tracks.map((track, index) => <div className="automation-track" key={index}><input type="checkbox" checked={track.enabled} onChange={(e) => { const tracks = structuredClone(project.automation_tracks); tracks[index].enabled = e.target.checked; onProjectChange({ ...project, automation_tracks: tracks }); }}/><select value={track.target} onChange={(e) => { const tracks = structuredClone(project.automation_tracks); tracks[index].target = e.target.value as ModulationTarget; onProjectChange({ ...project, automation_tracks: tracks }); }}>{targets.map((target) => <option value={target} key={target}>{pretty(target)}</option>)}</select><button onClick={() => addKeyframe(index)}>+ Key @ cursor</button>{track.keyframes.map((key, keyIndex) => <span className="keyframe" key={keyIndex}><input aria-label="Keyframe time" type="number" min="0" max={duration} step="0.1" value={key.time_seconds} onChange={(e) => { const tracks = structuredClone(project.automation_tracks); tracks[index].keyframes[keyIndex].time_seconds = Number(e.target.value); tracks[index].keyframes.sort((a, b) => a.time_seconds - b.time_seconds); onProjectChange({ ...project, automation_tracks: tracks }); }}/><input aria-label="Keyframe value" type="number" step="0.05" value={key.value} onChange={(e) => { const tracks = structuredClone(project.automation_tracks); tracks[index].keyframes[keyIndex].value = Number(e.target.value); onProjectChange({ ...project, automation_tracks: tracks }); }}/><button title="Remove keyframe" onClick={() => { const tracks = structuredClone(project.automation_tracks); tracks[index].keyframes.splice(keyIndex, 1); onProjectChange({ ...project, automation_tracks: tracks }); }}>×</button></span>)}</div>)}</div>
    <div className="marker-editor"><input id="marker-label" placeholder="Scene marker label"/><button disabled={!project} onClick={() => { if (!project) return; const input = document.querySelector<HTMLInputElement>("#marker-label"); const label = input?.value.trim(); if (!label) return; onProjectChange({ ...project, scene_markers: [...project.scene_markers, { time_seconds: cursorSeconds, label }].sort((a, b) => a.time_seconds - b.time_seconds) }); if (input) input.value = ""; }}>+ Marker @ cursor</button><span>{project?.scene_markers.map((marker) => `${marker.time_seconds.toFixed(1)}s ${marker.label}`).join(" · ")}</span></div>
  </div>;
}
