[package]
name = "particle-render"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
pollster = "0.4"
render-core = { path = "../../crates/render-core" }
simulation = { path = "../../crates/simulation" }

[lints]
workspace = true
